name: CI

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_GITHUB_ACTIONS_TOKEN }}
      - name: Get latest changes
        run: doctl cd portfolio && git pull origin master
      - name: Delete env file
        run: doctl rm .env.prod
      - name: Create env file
        run: doctl |
          touch .env.prod
          echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env.prod
          echo MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }} >> .env.prod
          echo MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }} >> .env.prod
          echo MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} >> .env.prod
          echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> .env.prod
          echo REACT_APP_HOST_IP_ADDRESS=${{ secrets.REACT_APP_HOST_IP_ADDRESS }} >> .env.prod
      - name: Stop current containers
        run: doctl docker stop $(docker ps -q -a)
      - name: Build new containers
        run: doctl docker-compose -f docker-compose.prod.yml --env-file .env.prod up --build -d